

/***********************************************************************
 * Header file function:
 * This header file provides functions and related data structures for
 * processing PLY binary files.
 * The main functions include writing the custom triangle mesh data
 * structure (triangle_part_t) to a PLY binary file and reading data from
 * a PLY binary file and filling it into the triangle mesh data structure.
 *
 * Author information:
 * Author's name: Xiangkui Zhang.
 * Author's email: zhangxk@dlut.edu.cn.
 * Author's phone number: 13614112028.
 *
 * Code statement:
 * The code in this header file is generated by the Douyin Doubao AI engine
 * under the guidance of the author.
 ***********************************************************************/

#ifndef PLY_IO_GUID_2F74C3A019B14F4298935D9F089E86B2
#define PLY_IO_GUID_2F74C3A019B14F4298935D9F089E86B2

#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace std {
typedef float float32_t;
}

namespace dcip_ply {
// Structure for storing triangle mesh information.
struct triangle_part_t {
    std::vector<float> points;        // Vertex information.
    std::vector<float> vertexNormals; // Vertex normals.
    std::vector<int> triangles;       // Triangle indices.

    // 节点数据 (Point Data)
    std::vector<float> vonmises; // vonmises应力 - 节点
    std::vector<float> DisX;     // DisX位移 - 节点
    std::vector<float> DisY;     // DisY位移 - 节点
    std::vector<float> DisZ;     // DisZ位移 - 节点
    std::vector<float> DisTotal; // 总位移 - 节点
    std::vector<float> SR11;     // SR11 x方向正应力 - 节点
    std::vector<float> SR22;     // SR22 y方向正应力 - 节点
    std::vector<float> SR33;     // SR33 z方向正应力 - 节点
    std::vector<float> SR12;     // SR12 x方向剪应力 - 节点
    std::vector<float> SR13;     // SR13 y方向剪应力 - 节点
    std::vector<float> SR23;     // SR23 z方向剪应力 - 节点
    std::vector<float> SS11;     // SS11 x方向正应力 - 节点
    std::vector<float> SS22;     // SS22 y方向正应力 - 节点
    std::vector<float> SS33;     // SS33 z方向正应力 - 节点
    std::vector<float> SS12;     // SS12 x方向剪应力 - 节点
    std::vector<float> SS13;     // SS13 y方向剪应力 - 节点
    std::vector<float> SS23;     // SS23 z方向剪应力 - 节点

    // [新增] 温度 - 节点
    std::vector<float> Temperature;

    // 单元数据 (Cell Data) - 每个三角形一个值
    std::vector<float> cell_vonmises1; // vonmises应力 - 单元
    std::vector<float> cell_vonmises;  // vonmises应力 - 单元
    std::vector<float> cell_DisX;      // DisX位移 - 单元
    std::vector<float> cell_DisY;      // DisY位移 - 单元
    std::vector<float> cell_DisZ;      // DisZ位移 - 单元
    std::vector<float> cell_DisTotal;  // 总位移 - 单元
    std::vector<float> cell_SR11;      // SR11 x方向正应力 - 单元
    std::vector<float> cell_SR22;      // SR22 y方向正应力 - 单元
    std::vector<float> cell_SR33;      // SR33 z方向正应力 - 单元
    std::vector<float> cell_SR12;      // SR12 x方向剪应力 - 单元
    std::vector<float> cell_SR13;      // SR13 y方向剪应力 - 单元
    std::vector<float> cell_SR23;      // SR23 z方向剪应力 - 单元
    std::vector<float> cell_SS11;      // SS11 x方向正应力 - 单元
    std::vector<float> cell_SS22;      // SS22 y方向正应力 - 单元
    std::vector<float> cell_SS33;      // SS33 z方向正应力 - 单元
    std::vector<float> cell_SS12;      // SS12 x方向剪应力 - 单元
    std::vector<float> cell_SS13;      // SS13 y方向剪应力 - 单元
    std::vector<float> cell_SS23;      // SS23 z方向剪应力 - 单元

    // [新增] 温度 - 单元
    std::vector<float> cell_Temperature;

    virtual ~triangle_part_t() {}
};

// Enumeration type for different states of PLY header parsing.
enum class PlyHeaderState {
        INITIAL,
        FOUND_PLY,
        FOUND_FORMAT,
        FOUND_ELEMENT_VERTEX,
        FOUND_ELEMENT_FACE,
        FOUND_END_HEADER
};

// Function for parsing PLY file header.
bool parsePLYHeader(std::ifstream &infile, size_t &numVertices,
                    size_t &numFaces) {
        PlyHeaderState state = PlyHeaderState::INITIAL;
        std::string line;
        while (std::getline(infile, line)) {
                switch (state) {
                case PlyHeaderState::INITIAL:
                        if (line == "ply") {
                                state = PlyHeaderState::FOUND_PLY;
                        } else {
                                return false;
                        }
                        break;
                case PlyHeaderState::FOUND_PLY:
                        if (line.find("format") == 0) {
                                state = PlyHeaderState::FOUND_FORMAT;
                        } else {
                                return false;
                        }
                        break;
                case PlyHeaderState::FOUND_FORMAT:
                        if (line.find("element vertex") == 0) {
                                sscanf(line.c_str(), "element vertex %zu",
                                       &numVertices);
                                state = PlyHeaderState::FOUND_ELEMENT_VERTEX;
                        } else {
                                return false;
                        }
                        break;
                case PlyHeaderState::FOUND_ELEMENT_VERTEX:
                        if (line.find("element face") == 0) {
                                sscanf(line.c_str(), "element face %zu",
                                       &numFaces);
                                state = PlyHeaderState::FOUND_ELEMENT_FACE;
                        }
                        break;
                case PlyHeaderState::FOUND_ELEMENT_FACE:
                        if (line == "end_header") {
                                return true;
                        }
                        break;
                }
        }
        return false;
}

// Implement htonl if the system doesn't have it.
inline uint32_t htonl(uint32_t hostlong) {
        uint32_t result = 0;
        result |= (hostlong & 0xFF) << 24;
        result |= ((hostlong >> 8) & 0xFF) << 16;
        result |= ((hostlong >> 16) & 0xFF) << 8;
        result |= (hostlong >> 24) & 0xFF;
        return result;
}

// Implement ntohl if the system doesn't have it.
inline uint32_t ntohl(uint32_t netlong) { return htonl(netlong); }

// Function for writing triangle_part_t structure representing mesh data
// to a PLY binary file.
inline bool writePLYBinary(const std::string &filename,
                           const triangle_part_t &mesh) {
        std::ofstream outfile(filename, std::ios::binary);
        if (!outfile) {
                return false;
        }
        // PLY file header.
        outfile << "ply\n";
        outfile << "format binary_big_endian 1.0\n";
        outfile << "element vertex " << mesh.points.size() / 3 << "\n";
        outfile << "property float32 x\n";
        outfile << "property float32 y\n";
        outfile << "property float32 z\n";
        outfile << "property float32 nx\n";
        outfile << "property float32 ny\n";
        outfile << "property float32 nz\n";
        outfile << "element face " << mesh.triangles.size() / 3 << "\n";
        outfile << "property list uint8 int32 vertex_indices\n";
        outfile << "end_header\n";
        // Write vertex data (coordinates and normals).
        for (size_t i = 0; i < mesh.points.size(); i += 3) {
                std::float32_t x = mesh.points[i];
                std::float32_t y = mesh.points[i + 1];
                std::float32_t z = mesh.points[i + 2];
                std::float32_t nx = mesh.vertexNormals[i];
                std::float32_t ny = mesh.vertexNormals[i + 1];
                std::float32_t nz = mesh.vertexNormals[i + 2];
                uint32_t x_big = htonl(*reinterpret_cast<uint32_t *>(&x));
                uint32_t y_big = htonl(*reinterpret_cast<uint32_t *>(&y));
                uint32_t z_big = htonl(*reinterpret_cast<uint32_t *>(&z));
                uint32_t nx_big = htonl(*reinterpret_cast<uint32_t *>(&nx));
                uint32_t ny_big = htonl(*reinterpret_cast<uint32_t *>(&ny));
                uint32_t nz_big = htonl(*reinterpret_cast<uint32_t *>(&nz));
                outfile.write(reinterpret_cast<const char *>(&x_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&y_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&z_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&nx_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&ny_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&nz_big),
                              sizeof(uint32_t));
        }
        // Write face data (triangle indices).
        for (size_t i = 0; i < mesh.triangles.size(); i += 3) {
                std::int8_t numVertices = 3;
                outfile.write(reinterpret_cast<const char *>(&numVertices),
                              sizeof(std::int8_t));
                uint32_t index1_big =
                    htonl(static_cast<uint32_t>(mesh.triangles[i]));
                uint32_t index2_big =
                    htonl(static_cast<uint32_t>(mesh.triangles[i + 1]));
                uint32_t index3_big =
                    htonl(static_cast<uint32_t>(mesh.triangles[i + 2]));
                outfile.write(reinterpret_cast<const char *>(&index1_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&index2_big),
                              sizeof(uint32_t));
                outfile.write(reinterpret_cast<const char *>(&index3_big),
                              sizeof(uint32_t));
        }
        outfile.close();
        return true;
}

// Function for reading data from a PLY binary file and filling it into
// the triangle_part_t structure.
inline bool readPLYBinary(const std::string &filename, triangle_part_t &mesh) {
        std::ifstream infile(filename, std::ios::binary);
        if (!infile) {
                return false;
        }
        size_t numVertices, numFaces;
        if (!parsePLYHeader(infile, numVertices, numFaces)) {
                return false;
        }
        mesh.points.resize(numVertices * 3);
        mesh.vertexNormals.resize(numVertices * 3);
        mesh.triangles.resize(numFaces * 3);
        // Read vertex data (coordinates and normals).
        for (size_t i = 0; i < numVertices; ++i) {
                uint32_t x_big, y_big, z_big, nx_big, ny_big, nz_big;
                infile.read(reinterpret_cast<char *>(&x_big), sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&y_big), sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&z_big), sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&nx_big),
                            sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&ny_big),
                            sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&nz_big),
                            sizeof(uint32_t));
                auto temp = ntohl(x_big);
                std::float32_t x = *reinterpret_cast<std::float32_t *>(&temp);
                temp = ntohl(y_big);
                std::float32_t y = *reinterpret_cast<std::float32_t *>(&temp);
                temp = ntohl(z_big);
                std::float32_t z = *reinterpret_cast<std::float32_t *>(&temp);
                temp = ntohl(nx_big);
                std::float32_t nx = *reinterpret_cast<std::float32_t *>(&temp);
                temp = ntohl(ny_big);
                std::float32_t ny = *reinterpret_cast<std::float32_t *>(&temp);
                temp = ntohl(nz_big);
                std::float32_t nz = *reinterpret_cast<std::float32_t *>(&temp);
                mesh.points[3 * i] = x;
                mesh.points[3 * i + 1] = y;
                mesh.points[3 * i + 2] = z;
                mesh.vertexNormals[3 * i] = nx;
                mesh.vertexNormals[3 * i + 1] = ny;
                mesh.vertexNormals[3 * i + 2] = nz;
        }
        // Read face data (triangle indices).
        for (size_t i = 0; i < numFaces; ++i) {
                std::int8_t numVertices;
                infile.read((char *)&numVertices, sizeof(std::int8_t));
                uint32_t index1_big, index2_big, index3_big;
                infile.read(reinterpret_cast<char *>(&index1_big),
                            sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&index2_big),
                            sizeof(uint32_t));
                infile.read(reinterpret_cast<char *>(&index3_big),
                            sizeof(uint32_t));
                int32_t index1 = static_cast<int32_t>(ntohl(index1_big));
                int32_t index2 = static_cast<int32_t>(ntohl(index2_big));
                int32_t index3 = static_cast<int32_t>(ntohl(index3_big));
                mesh.triangles[3 * i] = index1;
                mesh.triangles[3 * i + 1] = index2;
                mesh.triangles[3 * i + 2] = index3;
        }
        infile.close();
        return true;
}
} // namespace dcip_ply

#endif // PLY_IO_GUID_2F74C3A019B14F4298935D9F089E86B2